Switch to alpine + add missing deps
honestica/electron-release-server pull request #15
Opened 2020-09-19 12:44 UTC by dadicool

2020-09-20 11:25 UTC, dadicool commented
FYI - @DrGkill @mtparet si cette PR nous donne une image de base fonctionnelle, on pourra la maintenir par rapport aux vulns plus facilement,

2020-09-20 12:20 UTC, pierrickouw requested changes

2020-09-20 12:20 UTC, pierrickouw commented on Dockerfile
> +RUN apk add --update --no-cache python3 make git && ln -sf python3 /usr/bin/python
Pourquoi rajouter Python?

2020-09-20 12:29 UTC, dadicool commented on Dockerfile
> +RUN apk add --update --no-cache python3 make git && ln -sf python3 /usr/bin/python
le build ne marchait pas sans python :) je ne l'ai pas invente. Y a qq part dans le process de build besoin de python. 

Je peux aussi évoluer le build pour avoir un multi-stage build pour pas voir python dans l'image finale.

2020-09-23 15:33 UTC, pierrickouw approved these changes

2020-09-23 16:29 UTC, merged